GameGlamer/Controllers/DLCorLootDealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameGlamer.Data;
using GameGlamer.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Security.Claims;

namespace GameGlamer.Controllers
{
    public class DLCorLootDealsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DLCorLootDealsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DLCorLootDeals
        public async Task<IActionResult> Index()
        {
            List<DLCorLootDeal> dataList = new List<DLCorLootDeal>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://www.gamerpower.com/api/giveaways?type=loot"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    dataList = JsonConvert.DeserializeObject<List<DLCorLootDeal>>(apiResponse);
                }
            }
            return View(dataList);
           //return View(await _context.Enrollments.ToListAsync());
        }

        // GET: DLCorLootDeals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            DLCorLootDeal dLCorLootDeal = new DLCorLootDeal();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://www.gamerpower.com/api/giveaway?id=" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    dLCorLootDeal = JsonConvert.DeserializeObject<DLCorLootDeal>(apiResponse);
                }
            }
            if (dLCorLootDeal == null)
            {
                return NotFound();
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var items = _context.UserLoots.Where(e => e.userId == userId && e.gameId == dLCorLootDeal.id);
            if (items.Count() == 0)
            {
                ViewBag.isSaved = false;
            }
            else
            {
                ViewBag.isSaved = true;
            }

            return View(dLCorLootDeal);
        }


        public async Task<IActionResult> Save(String buttonAction, int itemId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var items = _context.UserLoots.Where(e => e.userId == userId && e.gameId == itemId);
            if (buttonAction == "save"
                && items.Count() == 0)
            {
                _context.UserLoots.Add(new UserLoot(userId, itemId));
                await _context.SaveChangesAsync();
            }
            else if (buttonAction == "unsave"
                && items.Count() > 0)
            {
                var userLoot = await _context.UserLoots.FindAsync(_context.UserLoots.SingleOrDefault(item => item.userId.Equals(userId) && item.gameId == itemId).id);
                _context.UserLoots.Remove(userLoot);
                await _context.SaveChangesAsync();
            }
            return Redirect("~/DLCorLootDeals/Details/" + itemId);
        }

        // GET: DLCorLootDeals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DLCorLootDeals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,title,worth,thumbnail,image,description,instructions,open_giveaway_url,published_date,type,platforms,end_date,users,status,gamerpower_url,open_giveaway")] DLCorLootDeal dLCorLootDeal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dLCorLootDeal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dLCorLootDeal);
        }

        // GET: DLCorLootDeals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dLCorLootDeal = await _context.DLCorLootDeals.FindAsync(id);
            if (dLCorLootDeal == null)
            {
                return NotFound();
            }
            return View(dLCorLootDeal);
        }

        // POST: DLCorLootDeals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,title,worth,thumbnail,image,description,instructions,open_giveaway_url,published_date,type,platforms,end_date,users,status,gamerpower_url,open_giveaway")] DLCorLootDeal dLCorLootDeal)
        {
            if (id != dLCorLootDeal.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dLCorLootDeal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DLCorLootDealExists(dLCorLootDeal.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dLCorLootDeal);
        }

        // GET: DLCorLootDeals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dLCorLootDeal = await _context.DLCorLootDeals
                .FirstOrDefaultAsync(m => m.id == id);
            if (dLCorLootDeal == null)
            {
                return NotFound();
            }

            return View(dLCorLootDeal);
        }

        // POST: DLCorLootDeals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dLCorLootDeal = await _context.DLCorLootDeals.FindAsync(id);
            _context.DLCorLootDeals.Remove(dLCorLootDeal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DLCorLootDealExists(int id)
        {
            return _context.DLCorLootDeals.Any(e => e.id == id);
        }

        public async Task<IActionResult> SavedLoot()
        {
            List<DLCorLootDeal> lootDeals = new List<DLCorLootDeal>();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var items = _context.UserLoots.Where(e => e.userId == userId).ToList();
            using (var httpClient = new HttpClient())
            {
                for (int i = 0; i < items.Count(); i++)
                {
                    using (var response = await httpClient.GetAsync("https://www.gamerpower.com/api/giveaway?id=" + items.ElementAt(i).gameId))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        lootDeals.Add(JsonConvert.DeserializeObject<DLCorLootDeal>(apiResponse));
                    }
                }
            }
            return View(lootDeals.AsEnumerable());
        }
    }
}

GameGlamer/Controllers/GameDealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameGlamer.Data;
using GameGlamer.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Security.Claims;

namespace GameGlamer.Controllers
{
    public class GameDealsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GameDealsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: GameDeals
        public async Task<IActionResult> Index()
        {
            List<GameDeal> dataList = new List<GameDeal>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://www.gamerpower.com/api/giveaways?type=game"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    dataList = JsonConvert.DeserializeObject<List<GameDeal>>(apiResponse);
                }
            }
            return View(dataList);
        }

        // GET: GameDeals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameDeal gameDeal = new GameDeal();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://www.gamerpower.com/api/giveaway?id=" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    gameDeal = JsonConvert.DeserializeObject<GameDeal>(apiResponse);
                }
            }
            if (gameDeal == null)
            {
                return NotFound();
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var items = _context.UserGames.Where(e => e.userId == userId && e.gameId == gameDeal.id);
            if(items.Count() == 0)
            {
                ViewBag.isSaved = false;
            }
            else
            {
                ViewBag.isSaved = true;
            }

            return View(gameDeal);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(String buttonAction, int itemId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var items = _context.UserGames.Where(e => e.userId == userId && e.gameId == itemId);
            if (buttonAction == "save"
                && items.Count() == 0)
            {
                _context.UserGames.Add(new UserGame(userId, itemId));
                await _context.SaveChangesAsync();
            }
            else if (buttonAction == "unsave"
                && items.Count() > 0)
            {
                var userGame = await _context.UserGames.FindAsync(_context.UserGames.SingleOrDefault(item => item.userId.Equals(userId) && item.gameId == itemId).id);
                _context.UserGames.Remove(userGame);
                await _context.SaveChangesAsync();
            }
            return Redirect("~/GameDeals/Details/" + itemId);
        }

        // GET: GameDeals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: GameDeals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,title,worth,thumbnail,image,description,instructions,open_giveaway_url,published_date,type,platforms,end_date,users,status,gamerpower_url,open_giveaway")] GameDeal gameDeal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gameDeal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gameDeal);
        }

        // GET: GameDeals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameDeal = await _context.GameDeals.FindAsync(id);
            if (gameDeal == null)
            {
                return NotFound();
            }
            return View(gameDeal);
        }

        // POST: GameDeals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,title,worth,thumbnail,image,description,instructions,open_giveaway_url,published_date,type,platforms,end_date,users,status,gamerpower_url,open_giveaway")] GameDeal gameDeal)
        {
            if (id != gameDeal.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gameDeal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameDealExists(gameDeal.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gameDeal);
        }

        // GET: GameDeals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameDeal = await _context.GameDeals
                .FirstOrDefaultAsync(m => m.id == id);
            if (gameDeal == null)
            {
                return NotFound();
            }

            return View(gameDeal);
        }

        // POST: GameDeals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gameDeal = await _context.GameDeals.FindAsync(id);
            _context.GameDeals.Remove(gameDeal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameDealExists(int id)
        {
            return _context.GameDeals.Any(e => e.id == id);
        }

        public async Task<IActionResult> SavedGames()
        {
            List<GameDeal> gameDeals = new List<GameDeal>();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var items = _context.UserGames.Where(e => e.userId == userId).ToList();
            using (var httpClient = new HttpClient())
            {
                for (int i = 0; i < items.Count(); i++)
                {
                    using (var response = await httpClient.GetAsync("https://www.gamerpower.com/api/giveaway?id=" + items.ElementAt(i).gameId))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        gameDeals.Add(JsonConvert.DeserializeObject<GameDeal>(apiResponse));
                    }
                }
            }
            return View(gameDeals.AsEnumerable());
        }


    }
}

GameGlamer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model HomeMainVM

<div class="text-center" style="min-height: 200vh">
    <h1 class="display-4">Welcome To <span class="text-courgette">GameGlam</span>!</h1>
    <p>Here you can observe game and loot giveaways, just like these observing the sea.</p>

    <div class="my_image_banner">
        <img class="banner_image" src="~/media/gifs/main_banner.gif" />
    </div>


    <div class="pb-2">
        <h3 class="m-0 text-black my_main_header">Popular</h3>
        <hr />
    </div>

    <div class="container">
        <div class="row">
            <!-- click="redirect(item.id)"  v-for="item in content" :key="item.id"-->
            @foreach (GameDeal gameDeal in Model.topGames)
            {
                <div class="col-3 pb-3">
                    <div class="card w-100">
                        <img class="card-img-top" src="@gameDeal.thumbnail" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title text-center">@gameDeal.title</h5>
                        </div>
                        <a asp-controller="GameDeals" asp-action="Details" asp-route-id="@gameDeal.id" class="stretched-link"></a>
                    </div>
                </div>
            }

        </div>
    </div>

    <div class="py-2">
        <h3 class="m-0 text-black my_main_header">Top Items</h3>
        <hr />
    </div>
    <div class="container">
        <nav class="nav justify-content-center">
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <button class="nav-link active" id="nav-games-tab" data-bs-toggle="tab" data-bs-target="#nav-games" type="button" role="tab" aria-controls="nav-games" aria-selected="true">Games</button>
                <button class="nav-link" id="nav-loot-tab" data-bs-toggle="tab" data-bs-target="#nav-loot" type="button" role="tab" aria-controls="nav-loot" aria-selected="false">Loot</button>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-games" role="tabpanel" aria-labelledby="nav-home-tab">
                <ul class="list-group">
                    @foreach (GameDeal gameDeal in Model.top16Games)
                    {
                        <li class="list-group-item my_list_item mb-2" tabindex="0">
                            <div class="row">
                                <div class="col-3">
                                    <img class="my_search_list_image d-block w-100" src="@gameDeal.thumbnail" alt="...">
                                </div>
                                <div class="col m-0 justify-content-start">
                                    <div class="text-left">
                                        <span class="item_primary_text">@gameDeal.title</span>
                                        <br />
                                        <span class="item_secondary_text">@gameDeal.platforms</span>
                                    </div>
                                </div>
                            </div>
                            <a asp-controller="GameDeals" asp-action="Details" asp-route-id="@gameDeal.id" class="stretched-link"></a>
                        </li>
                    }
                </ul>
            </div>
            <div class="tab-pane fade" id="nav-loot" role="tabpanel" aria-labelledby="nav-profile-tab">
                <ul class="list-group">
                    @foreach (DLCorLootDeal lootDeal in Model.top16Loot)
                    {
                    <li class="list-group-item my_list_item mb-2" tabindex="0">
                        <div class="row">
                            <div class="col-3">
                                <img class="my_search_list_image d-block w-100" src="@lootDeal.thumbnail" alt="...">
                            </div>
                            <div class="col m-0 justify-content-start">
                                <div class="text-left">
                                    <span class="item_primary_text">@lootDeal.title</span>
                                    <br />
                                    <span class="item_secondary_text">@lootDeal.platforms</span>
                                </div>
                            </div>
                        </div>
                        <a asp-controller="DLCorLootDeals" asp-action="Details" asp-route-id="@lootDeal.id" class="stretched-link"></a>
                    </li>
                    }
                </ul>
            </div>
        </div>
    </div>



</div>

<!--


                <ul class="mdc-list mdc-list--two-line mdc-list--image-list">
                    <li click="redirect(item.id)" class="mdc-list-item" tabindex="0" v-for="item in loot" :key="item.id">
                        <div class="mdc-list--icon-list m-1">
                            <div class="my_search_list_image">
                                <img v-bind:src="item.thumbnail" class="d-block w-100" alt="...">
                            </div>
                        </div>
                        <span class="mdc-list-item__ripple"></span>
                        <span class="mdc-list-item__text">
                            <span class="mdc-list-item__primary-text"></span>
                            <span class="mdc-list-item__secondary-text"></span>
                        </span>
                        <div class="w-100"></div>
                    </li>
                    <div class="mdc-list-divider mt-1 mb-1"></div>
                </ul>
-->

GameGlamer/Views/Home/List.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@{
    Layout = "_Layout";
}

@model SearchVM

<div class="text-center">
    <div class="pb-2">
        <div class="d-flex justify-content-center h-100">
            <form class="form-inline" asp-controller="Home" asp-action="Search" method="get">
                <div class="searchbar">
                    <input class="form-control search_input" type="text" name="search_str" placeholder="Search Games...">
                    <button class="btn search_icon" type="submit"><i class="fas fa-search"></i></button>
                </div>
            </form>
        </div>
        <hr />
    </div>

    <div class="container">
        @if (!((Model.searchedGames == null || Model.searchedGames.Count() == 0) && (Model.searchedLoot == null || Model.searchedLoot.Count() == 0)))
        {
            <nav class="nav justify-content-center">
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-games-tab" data-bs-toggle="tab" data-bs-target="#nav-games" type="button" role="tab" aria-controls="nav-games" aria-selected="true">Games</button>
                    <button class="nav-link" id="nav-loot-tab" data-bs-toggle="tab" data-bs-target="#nav-loot" type="button" role="tab" aria-controls="nav-loot" aria-selected="false">Loot</button>
                </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-games" role="tabpanel" aria-labelledby="nav-home-tab">
                    @if (Model.searchedGames != null)
                    {
                        <ul class="list-group">
                            @foreach (GameDeal gameDeal in Model.searchedGames)
                            {
                                <li class="list-group-item my_list_item mb-2" tabindex="0">
                                    <div class="row">
                                        <div class="col-3">
                                            <img class="my_search_list_image d-block w-100" src="@gameDeal.thumbnail" alt="...">
                                        </div>
                                        <div class="col m-0 justify-content-start">
                                            <div class="text-left">
                                                <span class="item_primary_text">@gameDeal.title</span>
                                                <br />
                                                <span class="item_secondary_text">@gameDeal.platforms</span>
                                            </div>
                                        </div>
                                    </div>
                                    <a asp-controller="GameDeals" asp-action="Details" asp-route-id="@gameDeal.id" class="stretched-link h-100"></a>
                                </li>
                            }
                        </ul>
                    }
                    else if (!String.IsNullOrEmpty(Model.search_str))
                    {
                        <h3 class="m-0 text-black my_main_header">No Games Found!</h3>
                    }
                </div>
                <div class="tab-pane fade" id="nav-loot" role="tabpanel" aria-labelledby="nav-profile-tab">
                    @if (Model.searchedLoot != null)
                    {
                        <ul class="list-group">
                            @foreach (DLCorLootDeal lootDeal in Model.searchedLoot)
                            {
                                <li class="list-group-item my_list_item mb-2" tabindex="0">
                                    <div class="row">
                                        <div class="col-3">
                                            <img class="my_search_list_image d-block w-100" src="@lootDeal.thumbnail" alt="...">
                                        </div>
                                        <div class="col m-0 justify-content-start">
                                            <div class="text-left">
                                                <span class="item_primary_text">@lootDeal.title</span>
                                                <br />
                                                <span class="item_secondary_text">@lootDeal.platforms</span>
                                            </div>
                                        </div>
                                    </div>
                                    <a asp-controller="DLCorLootDeals" asp-action="Details" asp-route-id="@lootDeal.id" class="stretched-link"></a>
                                </li>
                            }
                        </ul>
                    }
                    else if (!String.IsNullOrEmpty(Model.search_str))
                    {
                        <h3 class="m-0 text-black my_main_header">No Loot Found!</h3>
                    }
                </div>
            </div>
        }
        else
        {
            @if (!String.IsNullOrEmpty(Model.search_str))
            {
                <h3 class="m-0 text-black my_main_header">Nothing Was Found!</h3>
            }
            else
            {
                <h3 class="m-0 text-black my_main_header">Start Searching Something</h3>
            }
        }
    </div>

    </div>